# Generated by Django 3.0.3 on 2020-03-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Enterprise name')),
                ('users', models.ManyToManyField(help_text='User id mapping to enterprise table', to='users.User')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('enterprise', models.ForeignKey(help_text='Enterprise id', on_delete=models.deletion.PROTECT,
                                                 to='enterprise.Enterprise')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh token')),
                ('org_id', models.CharField(max_length=255, unique=True, verbose_name='org id')),
                ('org_name', models.TextField(blank=True, null=True, verbose_name='Org name')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('enterprise', models.ForeignKey(help_text='Enterprise id', on_delete=models.deletion.PROTECT,
                                                 to='enterprise.Enterprise')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Status')),
                ('total_rows', models.IntegerField(max_length=255, verbose_name='No. of rows', default=0)),
                ('total_orgs', models.IntegerField(max_length=255, verbose_name='No. of orgs', default=0)),
                ('gsheet_link', models.TextField(blank=True, null=True, verbose_name='Org name')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at time')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
