# Generated by Django 3.0.3 on 2020-06-02 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Enterprise name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created at time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated at time')),
                ('users', models.ManyToManyField(help_text='User id mapping to enterprise table', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh token')),
                ('org_id', models.CharField(max_length=255, unique=True, verbose_name='org id')),
                ('org_name', models.TextField(blank=True, null=True, verbose_name='Org name')),
                ('added_by', models.TextField(blank=True, null=True, verbose_name='Added by')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created at time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated at time')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprise.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True, verbose_name='Status')),
                ('total_rows', models.IntegerField(default=0, verbose_name='No. of rows')),
                ('total_orgs', models.IntegerField(default=0, verbose_name='No. of orgs')),
                ('google_sheets_link', models.TextField(blank=True, null=True, verbose_name='Google sheets link')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created at time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated at time')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprise.Enterprise')),
            ],
        ),
    ]
