# Generated by Django 3.0.3 on 2020-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='job_id',
            field=models.CharField(default='', help_text='Fyle job id', max_length=255),
            preserve_default=False,
        ),
    ]
